spring:
#redis配置
  redis:
    host: 10.6.135.113
    port: 8081
  #mysql
  datasource:
    username: root
    password: A61RSTBY
    url: jdbc:mysql://10.2.132.173:64871/studio_sigh_up_db?characterEncoding=utf8
file:
  uploadPath: /usr/repository